# Active default profile
spring.profiles.active: dev

# Disable banner at project start
spring.main.banner-mode: "off"

# Data source config
spring.datasource.url: jdbc:sqlserver://localhost:1433;database=master;schema=cuentame;
spring.datasource.username: sa
spring.datasource.password: Aa12Bb34*
spring.datasource.driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.database-platform: org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true
spring.jpa.properties.hibernate.default_schema: cuentame
spring.jpa.open-in-view: false

# HikariCP settings (pool datasource)
spring.datasource.hikari.connection-timeout: 60000
spring.datasource.hikari.maximum-pool-size: 5

#Tomcat config
server.port: 8080
server.compression.enabled: true
server.compression.mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css

# Rest module
server.servlet.contextPath: /cuentame-rest

# FLYWAY (FlywayProperties)
spring.flyway.baseline-version: 1 # Version to start migration
spring.flyway.check-location: true # Whether to check that migration scripts location exists.
spring.flyway.enabled: true # Whether to enable flyway.
spring.flyway.encoding: UTF-8 #
spring.flyway.locations: "classpath:/db/migration/, classpath:/db/migrationLOCAL/" # The locations of migrations scripts.
spring.flyway.schemas: cuentame
spring.flyway.validate-on-migrate: true
spring.flyway.out-of-order: true
spring.flyway.placeholders.sch: cuentame

# Log config
logging.path: /opt/tomcat/logs
logging.file: /opt/tomcat/logs/cuentame.log
logging.level.ROOT: INFO
logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql: DEBUG